-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 15:56:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema huwebshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema huwebshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `huwebshop` DEFAULT CHARACTER SET utf8 ;
USE `huwebshop` ;

-- -----------------------------------------------------
-- Table `huwebshop`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huwebshop`.`brand` ;

CREATE TABLE IF NOT EXISTS `huwebshop`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huwebshop`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huwebshop`.`products` ;

CREATE TABLE IF NOT EXISTS `huwebshop`.`products` (
  `id` VARCHAR(255) NOT NULL,
  `brand_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `targetaudience` VARCHAR(255) NULL,
  `category` VARCHAR(255) NULL,
  `sub_category` VARCHAR(255) NULL,
  `sub_sub_category` VARCHAR(255) NULL,
  `msrp` VARCHAR(45) NULL,
  `discount` VARCHAR(45) NULL,
  `sellingprice` VARCHAR(45) NULL,
  `deal` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_brand1_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `huwebshop`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huwebshop`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huwebshop`.`profiles` ;

CREATE TABLE IF NOT EXISTS `huwebshop`.`profiles` (
  `id` VARCHAR(255) NOT NULL,
  `order_amount` INT NULL DEFAULT 0,
  `latest` DATETIME NULL,
  `segment` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huwebshop`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huwebshop`.`sessions` ;

CREATE TABLE IF NOT EXISTS `huwebshop`.`sessions` (
  `browser_id` VARCHAR(255) NOT NULL,
  `profiles_id` VARCHAR(255) NOT NULL,
  `segment` VARCHAR(45) NULL,
  `starttime` DATETIME NULL,
  `endtime` DATETIME NULL,
  `devicetype` VARCHAR(45) NULL,
  PRIMARY KEY (`profiles_id`),
  INDEX `fk_sessions_profiles1_idx` (`profiles_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_profiles1`
    FOREIGN KEY (`profiles_id`)
    REFERENCES `huwebshop`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huwebshop`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huwebshop`.`cart` ;

CREATE TABLE IF NOT EXISTS `huwebshop`.`cart` (
  `products_id` VARCHAR(255) NOT NULL,
  `sessions_profiles_id` VARCHAR(255) NOT NULL,
  `bought` TINYINT NOT NULL,
  PRIMARY KEY (`products_id`, `sessions_profiles_id`),
  INDEX `fk_products_has_sessions_products_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_cart_sessions1_idx` (`sessions_profiles_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_sessions_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `huwebshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_sessions1`
    FOREIGN KEY (`sessions_profiles_id`)
    REFERENCES `huwebshop`.`sessions` (`profiles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
